name: Deploy to Staging

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - staging-eu

jobs:
  deploy-backend:
    name: Deploy Backend to Staging
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: cd backend && npm ci

    - name: Run tests
      run: cd backend && npm test

    - name: Build application
      run: cd backend && npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
        aws-region: ${{ vars.AWS_REGION_STAGING }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push backend image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: buy-sell-platform-backend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd backend
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster staging-cluster --service backend-service --force-new-deployment

    - name: Run database migrations
      run: |
        cd backend
        npx sequelize-cli db:migrate --env staging

    - name: Health check
      run: |
        echo "Waiting for service to be healthy..."
        sleep 30
        curl -f https://staging-api.buy-sell-platform.com/health || exit 1

  deploy-frontend:
    name: Deploy Frontend to Staging
    runs-on: ubuntu-latest
    environment: staging
    needs: deploy-backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: cd frontend && npm ci

    - name: Run tests
      run: cd frontend && npm test

    - name: Build application
      env:
        NEXT_PUBLIC_API_URL: ${{ vars.STAGING_API_URL }}
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.STAGING_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.STAGING_SUPABASE_ANON_KEY }}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STAGING_STRIPE_PUBLISHABLE_KEY }}
      run: cd frontend && npm run build

    - name: Deploy to Vercel
      uses: vercel/action@v28
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_STAGING }}
        working-directory: ./frontend
        vercel-args: '--env NEXT_PUBLIC_API_URL=${{ vars.STAGING_API_URL }}'

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
      with:
        args: deploy --prod --dir=frontend/dist
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run API integration tests
      run: |
        cd backend/tests/integration
        npm install
        API_BASE_URL=${{ vars.STAGING_API_URL }} npm run test:staging

    - name: Run end-to-end tests
      run: |
        cd frontend/tests/e2e
        npm install
        BASE_URL=${{ vars.STAGING_FRONTEND_URL }} npm run test:staging

    - name: Performance test
      run: |
        cd backend/tests/performance
        artillery run staging-load-test.yml --target ${{ vars.STAGING_API_URL }}

  notify:
    name: Notify Team
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend, integration-tests]
    if: always()
    
    steps:
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 🚀 Deployment to Staging ${{ job.status }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 'Staging Deployment - ${{ job.status }}'
        body: |
          Deployment to staging environment has completed with status: ${{ job.status }}
          
          Commit: ${{ github.sha }}
          Branch: ${{ github.ref }}
          Triggered by: ${{ github.actor }}
          
          Backend URL: ${{ vars.STAGING_API_URL }}
          Frontend URL: ${{ vars.STAGING_FRONTEND_URL }}
        to: ${{ secrets.DEPLOYMENT_NOTIFICATION_EMAIL }}
        from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
