name: CI - Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18.x'
  DATABASE_URL: 'postgresql://test:test@localhost:5432/testdb'

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        component: [backend, frontend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: ${{ matrix.component }}

    - name: Install dependencies
      run: |
        cd ${{ matrix.component }}
        npm ci

    - name: Run linting
      run: |
        cd ${{ matrix.component }}
        npm run lint

    - name: Run tests
      run: |
        cd ${{ matrix.component }}
        npm run test:ci

    - name: Run security audit
      run: |
        cd ${{ matrix.component }}
        npm audit --audit-level moderate

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.component }}
        path: |
          ${{ matrix.component }}/coverage/
          ${{ matrix.component }}/test-results/
        retention-days: 7

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    strategy:
      matrix:
        component: [backend, frontend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: ${{ matrix.component }}

    - name: Install dependencies
      run: |
        cd ${{ matrix.component }}
        npm ci

    - name: Build application
      run: |
        cd ${{ matrix.component }}
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.component }}
        path: |
          ${{ matrix.component }}/dist/
          ${{ matrix.component }}/build/
        retention-days: 7

  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        tags: buysell-platform/backend:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        tags: buysell-platform/frontend:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: [lint-and-test, build, docker-build]
    if: always()
    
    steps:
    - name: Notify Slack on Failure
      if: needs.lint-and-test.result == 'failure' || needs.build.result == 'failure' || needs.docker-build.result == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#ci-cd'
        text: 'CI Pipeline Failed for ${{ github.ref }}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
