name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'
      force_migration:
        description: 'Force database migration'
        type: boolean
        default: false
  release:
    types: [published]

env:
  AWS_REGION: 'us-east-1'
  ENVIRONMENT: 'production'

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy Infrastructure
      run: |
        cd terraform
        terraform init -backend-config=environments/production/backend.hcl
        terraform workspace select production || terraform workspace new production
        terraform apply -auto-approve -var-file=environments/production/terraform.tfvars

    - name: Deploy Backend
      run: |
        aws ecs update-service \
          --cluster buy-sell-production \
          --service backend-service \
          --force-new-deployment

    - name: Deploy Frontend
      run: |
        aws ecs update-service \
          --cluster buy-sell-production \
          --service frontend-service \
          --force-new-deployment

    - name: Run Database Migrations
      if: ${{ github.event.inputs.force_migration == 'true' }}
      run: |
        aws ecs run-task \
          --cluster buy-sell-production \
          --task-definition migration-task \
          --launch-type FARGATE \
          --network-configuration "awsvpcConfiguration={subnets=[${{ secrets.PRODUCTION_SUBNETS }}],securityGroups=[${{ secrets.PRODUCTION_SG }}],assignPublicIp=DISABLED}"

    - name: Wait for Services
      run: |
        echo "Waiting for services to become stable..."
        sleep 180

    - name: Health Check
      run: |
        curl -f ${{ secrets.PRODUCTION_URL }}/health || exit 1
        curl -f ${{ secrets.PRODUCTION_URL }}/api/health || exit 1

    - name: Notify Success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        channel: '#production-deployments'
        text: 'Production deployment completed successfully! Version: ${{ github.event.inputs.version }}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#production-deployments'
        text: 'Production deployment failed! Please check logs.'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
